// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Store.Infra.Db.AppDb;

#nullable disable

namespace Store.Infra.Db.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251214120151_Add1")]
    partial class Add1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Store.Domain.Core.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "الکترونیک"
                        },
                        new
                        {
                            Id = 2,
                            Title = "مد و پوشاک"
                        },
                        new
                        {
                            Id = 3,
                            Title = "خانه و آشپزخانه"
                        },
                        new
                        {
                            Id = 4,
                            Title = "زیبایی و بهداشت"
                        },
                        new
                        {
                            Id = 5,
                            Title = "ورزش و سلامت"
                        },
                        new
                        {
                            Id = 6,
                            Title = "کتاب و لوازم تهریر"
                        });
                });

            modelBuilder.Entity("Store.Domain.Core.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Store.Domain.Core.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Store.Domain.Core.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Count = 5,
                            Description = "گوشی مدرن",
                            Image = "/File/ایفون 17.jpg",
                            Name = "آیفون 17 پرو",
                            Price = 300000000m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Count = 10,
                            Description = "گوشی مدرن",
                            Image = "/File/16 پرو.jpg",
                            Name = "آیفون 16 پرو",
                            Price = 200000000m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Count = 3,
                            Description = "گوشی مدرن",
                            Image = "/File/ایفون 16.jpg",
                            Name = "آیفون 16",
                            Price = 120000000m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Count = 6,
                            Description = "گوشی مدرن",
                            Image = "/File/15 پ.jpg",
                            Name = "آیفون 15 پرو",
                            Price = 150000000m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Count = 4,
                            Description = "گوشی مدرن",
                            Image = "/File/15 ن.jpg",
                            Name = "آیفون 15",
                            Price = 90000000m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Count = 15,
                            Description = "لپتاپ مدرن",
                            Image = "/File/اچ پی.jpg",
                            Name = "لپ تاپ اچ پی",
                            Price = 200000000m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Count = 12,
                            Description = "لپتاپ مدرن",
                            Image = "/File/لنوو.jpg",
                            Name = "لپتاب لنوو",
                            Price = 100000000m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            Count = 7,
                            Description = "پی اس پرو",
                            Image = "/File/پیاس5.jpg",
                            Name = "پی اس 5",
                            Price = 100000000m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            Count = 12,
                            Description = "لپتاپ مدرن",
                            Image = "/File/لنوو.jpg",
                            Name = "لپتاب لنوو",
                            Price = 100000000m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            Count = 10,
                            Description = "ایرپاد با کیفیت عالی",
                            Image = "/File/ایرپاد ایفون.jpg",
                            Name = "ایرپاد پرو مدل 1",
                            Price = 3500000m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 1,
                            Count = 8,
                            Description = "نسل جدید ایرپاد",
                            Image = "/File/ایرپاد 1.jpg",
                            Name = "ایرپاد پرو مدل 2",
                            Price = 4200000m
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 1,
                            Count = 18,
                            Description = "کول پد حرفه‌ای",
                            Image = "/File/کول پد.jpg",
                            Name = "کول پد ساده مدل 2",
                            Price = 750000m
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 1,
                            Count = 25,
                            Description = "کول پد سبک",
                            Image = "/File/کول پد 2.jpg",
                            Name = "کول پد ساده مدل 3",
                            Price = 500000m
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 1,
                            Count = 17,
                            Description = "موس بی سیم",
                            Image = "/File/موس.jpg",
                            Name = "موس بی‌سیم 3",
                            Price = 550000m
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 1,
                            Count = 30,
                            Description = "پد موس نرم",
                            Image = "/File/پد موس.jpg",
                            Name = "پد موس طرح 1",
                            Price = 150000m
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 1,
                            Count = 28,
                            Description = "پد موس ضد لغزش",
                            Image = "/File/پد موس2.jpg",
                            Name = "پد موس طرح 2",
                            Price = 180000m
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 1,
                            Count = 22,
                            Description = "پد موس گیمینگ",
                            Image = "/File/پد موس 1.jpg",
                            Name = "پد موس طرح 3",
                            Price = 200000m
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 2,
                            Count = 12,
                            Description = "لباس زنانه شیک",
                            Image = "/File/لباس ز1.jpg",
                            Name = "لباس زنانه مدل 1",
                            Price = 450000m
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 2,
                            Count = 10,
                            Description = "لباس مجلسی",
                            Image = "/File/لباس ز2.jpg",
                            Name = "لباس زنانه مدل 2",
                            Price = 520000m
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 2,
                            Count = 9,
                            Description = "پیراهن مردانه",
                            Image = "/File/لباس1.jpg",
                            Name = "لباس مردانه مدل 2",
                            Price = 620000m
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 2,
                            Count = 13,
                            Description = "لباس اسپرت",
                            Image = "/File/لباس.jpg",
                            Name = "لباس مردانه مدل 3",
                            Price = 530000m
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 2,
                            Count = 10,
                            Description = "لباس کودک",
                            Image = "/File/لباس ب2.jpg",
                            Name = "لباس بچه‌گانه مدل 1",
                            Price = 300000m
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 2,
                            Count = 14,
                            Description = "لباس کودک",
                            Image = "/File/لباس ب1.jpg",
                            Name = "لباس بچه‌گانه مدل 2",
                            Price = 330000m
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 2,
                            Count = 12,
                            Description = "کفش روزمره",
                            Image = "/File/کفش2.jpg",
                            Name = "کفش مدل 4",
                            Price = 760000m
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 2,
                            Count = 9,
                            Description = "کفش اسپرت",
                            Image = "/File/کفش5.jpg",
                            Name = "کفش مدل 5",
                            Price = 890000m
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 2,
                            Count = 8,
                            Description = "کیف دستی",
                            Image = "/File/کیف1.jpeg",
                            Name = "کیف مدل 1",
                            Price = 550000m
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 2,
                            Count = 7,
                            Description = "کیف دستی",
                            Image = "/File/کیف2.jpg",
                            Name = "کیف مدل 2",
                            Price = 600000m
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 2,
                            Count = 10,
                            Description = "کیف دستی",
                            Image = "/File/کیف3.jpg",
                            Name = "کیف مدل 3",
                            Price = 450000m
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 3,
                            Count = 6,
                            Description = "قوری مقاوم",
                            Image = "/File/قوری.jpeg",
                            Name = "قوری شیشه ای",
                            Price = 300000m
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 3,
                            Count = 2,
                            Description = "مبل مدرن",
                            Image = "/File/مبل 1.jpg",
                            Name = "مبل مدل 1",
                            Price = 6000000m
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 3,
                            Count = 2,
                            Description = "مبل مدرن",
                            Image = "/File/مبل 3.jpg",
                            Name = "مبل مدل 2",
                            Price = 7200000m
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 3,
                            Count = 1,
                            Description = "مبل مدرن",
                            Image = "/File/مبل2.jpg",
                            Name = "مبل مدل 3",
                            Price = 6800000m
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 3,
                            Count = 2,
                            Description = "تخت دو نفره",
                            Image = "/File/تخت1.jpg",
                            Name = "تخت خواب 1",
                            Price = 5000000m
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 3,
                            Count = 3,
                            Description = "تخت یک نفره",
                            Image = "/File/تخت2.jpg",
                            Name = "تخت خواب 2",
                            Price = 4200000m
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 3,
                            Count = 1,
                            Description = "تخت کلاسیک",
                            Image = "/File/تخت3.jpg",
                            Name = "تخت خواب 3",
                            Price = 6800000m
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 4,
                            Count = 10,
                            Description = "رژ لب بادوام",
                            Image = "/File/رژ.jpg",
                            Name = "رژ لب",
                            Price = 150000m
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 4,
                            Count = 20,
                            Description = "شامپو تقویتی",
                            Image = "/File/شامپو1.jpg",
                            Name = "شامپو مدل 1",
                            Price = 120000m
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 4,
                            Count = 18,
                            Description = "شامپو نرم‌کننده",
                            Image = "/File/شامپو.jpg",
                            Name = "شامپو مدل 2",
                            Price = 130000m
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 4,
                            Count = 18,
                            Description = "شوینده",
                            Image = "/File/شوینده2.jpg",
                            Name = "شوینده مدل 2",
                            Price = 130000m
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 5,
                            Count = 6,
                            Description = "دمبل ورزشی",
                            Image = "/File/دمبل.jpg",
                            Name = "دمبل 5 کیلویی",
                            Price = 350000m
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 5,
                            Count = 12,
                            Description = "طناب سبک",
                            Image = "/File/طناب.jpg",
                            Name = "طناب ورزشی",
                            Price = 90000m
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 5,
                            Count = 7,
                            Description = "کمربند بدنسازی",
                            Image = "/File/کمربندورزشی.jpg",
                            Name = "کمربند ورزشی",
                            Price = 200000m
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 6,
                            Count = 10,
                            Description = "کتاب داستانی",
                            Image = "/File/داستانی.jpg",
                            Name = "کتاب 1",
                            Price = 120000m
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 6,
                            Count = 9,
                            Description = "کتاب آموزشی",
                            Image = "/File/اموزشی.jpg",
                            Name = "کتاب 2",
                            Price = 150000m
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 6,
                            Count = 8,
                            Description = "کتاب روانشناسی",
                            Image = "/File/کتاب2.jpg",
                            Name = "کتاب 3",
                            Price = 180000m
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 6,
                            Count = 12,
                            Description = "کتاب روانشناسی",
                            Image = "/File/کتاب4.jpg",
                            Name = "کتاب 4",
                            Price = 110000m
                        });
                });

            modelBuilder.Entity("Store.Domain.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal>("Wallet")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "mahdi@gmail.com",
                            FullName = "مهدی رضایی",
                            IsActive = true,
                            Password = "1234567",
                            Role = 0,
                            Username = "mahdirr",
                            Wallet = 1000000000m
                        },
                        new
                        {
                            Id = 2,
                            Email = "fatemeh@gmail.com",
                            FullName = "فاطمه محمدی",
                            IsActive = true,
                            Password = "1234567",
                            Role = 1,
                            Username = "fatemehm",
                            Wallet = 500000000m
                        },
                        new
                        {
                            Id = 3,
                            Email = "hasan@gmail.com",
                            FullName = "حسن نوری",
                            IsActive = true,
                            Password = "1234567",
                            Role = 1,
                            Username = "hasannori",
                            Wallet = 200000000m
                        });
                });

            modelBuilder.Entity("Store.Domain.Core.Entities.Order", b =>
                {
                    b.HasOne("Store.Domain.Core.Entities.User", "User")
                        .WithMany("orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Store.Domain.Core.Entities.OrderItem", b =>
                {
                    b.HasOne("Store.Domain.Core.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Store.Domain.Core.Entities.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Store.Domain.Core.Entities.Product", b =>
                {
                    b.HasOne("Store.Domain.Core.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Store.Domain.Core.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Store.Domain.Core.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Store.Domain.Core.Entities.Product", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Store.Domain.Core.Entities.User", b =>
                {
                    b.Navigation("orders");
                });
#pragma warning restore 612, 618
        }
    }
}
